export const config = {
  charge: {
    title: '페이 충전 내역',
    description: '충전 일시와 금액을 한눈에 확인해보세요.',
    historyMent: '결제 내역',
    history: [
      { label: '결제 금액', key: 'paymentAmount' },
      { label: '할인된 금액', key: 'discountAmount' },
      { label: '최종 결제 금액', key: 'finalPaymentAmount' },
    ],
    payMent: '충전 다챠페이',
    isMinus: false,
    extra: [
      { label: '결제 번호', key: 'orderId' },
      { label: '충전 시간', key: 'chargedAt' },
      { label: '충전 방식', key: 'payTypeName' },
      { label: '총 다챠페이', key: 'finalUserPay' },
    ],
  },
  refund: {
    title: '페이 환전 내역',
    description: '환전 일시와 금액을 한눈에 확인해보세요.',
    historyMent: '환전 내역',
    history: [
      { label: '환전 금액', key: 'exchangeAmount' },
      { label: '수수료', key: 'fee' },
      { label: '최종 환전 금액', key: 'finalExchangeAmount' },
    ],
    payMent: '환전 다챠페이',
    isMinus: true,
    extra: [
      { label: '환전 번호', key: 'exchangeHistoryId' },
      { label: '환전 시간', key: 'exchangedAt' },
      { label: '환전 계좌', key: 'exchangeAccountWithBank' },
      { label: '총 다챠페이', key: 'finalUserPay' },
    ],
  },
  buy: {
    title: '거래 내역 (구매)',
    description: '거래 일시와 금액을 한눈에 확인해보세요.',
    historyMent: null,
    history: [],
    payMent: '거래 다챠페이',
    isMinus: true,
    extra: [
      { label: '거래 데이터', key: 'dataAmount' },
      { label: '거래 번호', key: 'transactionHistoryId' },
      { label: '거래 시간', key: 'transactedAt' },
      { label: '통신사', key: 'telecom' },
      { label: '총 다챠페이', key: 'finalUserPay' },
    ],
  },
  sell: {
    title: '거래 내역 (판매)',
    description: '거래 일시와 금액을 한눈에 확인해보세요.',
    historyMent: null,
    history: [],
    payMent: '거래 다챠페이',
    isMinus: false,
    extra: [
      { label: '거래 데이터', key: 'dataAmount' },
      { label: '거래 번호', key: 'transactionHistoryId' },
      { label: '거래 시간', key: 'transactedAt' },
      { label: '통신사', key: 'telecom' },
      { label: '총 다챠페이', key: 'finalUserPay' },
    ],
  },
} as const
